version: 1
disable_existing_loggers: false
formatters:
  default:
    fmt: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stderr
loggers:
  uvicorn.error:
    level: INFO
    handlers: [console]
    propagate: no
  uvicorn.access:
    level: INFO
    handlers: [console]
    propagate: no
  stereo_asr_api: # Match the logger name used in your python script if specific
    level: INFO
    handlers: [console]
    propagate: yes
