version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"

handlers:
  file:
    class: logging.FileHandler
    formatter: default
    filename: ./uvicorn.log
    mode: a

loggers:
  uvicorn:
    handlers: [file]
    level: INFO
    propagate: False

  uvicorn.error:
    handlers: [file]
    level: INFO
    propagate: False

  uvicorn.access:
    handlers: [file]
    level: INFO
    propagate: False

root:
  handlers: [file]
  level: INFO